import { StyleSheet } from "react-native";

export const themeColors = {
  background: "#fff7fb",
  surface: "#ffffff",
  surfaceElevated: "#fef0fb",
  border: "#f2cce5",
  borderStrong: "#f39bcc",
  textPrimary: "#5c3b70",
  textSecondary: "#7e5a95",
  textMuted: "#9b7db0",
  textPlaceholder: "#b598c8",
  accent: "#ff8fc6",
  accentStrong: "#ff73b8",
  accentSoft: "#ffe6f4",
  error: "#de5c81",
  white: "#ffffff",
};

export const calendarTheme = {
  calendarBackground: themeColors.surface,
  monthTextColor: themeColors.textPrimary,
  dayTextColor: themeColors.textSecondary,
  textDisabledColor: "#d3b8c9",
  selectedDayBackgroundColor: themeColors.accent,
  selectedDayTextColor: themeColors.white,
  todayTextColor: themeColors.accent,
  arrowColor: themeColors.accent,
};

export const appStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: themeColors.background,
  },
  screenHeader: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 8,
    gap: 6,
  },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: themeColors.textPrimary,
  },
  stepTitle: {
    fontSize: 14,
    color: themeColors.textSecondary,
    fontWeight: "700",
  },
  stepperRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    gap: 12,
    marginTop: 2,
    paddingRight: 8,
  },
  stepperItem: {
    alignItems: "center",
    gap: 3,
  },
  stepDot: {
    width: 26,
    height: 26,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  stepDotActive: {
    borderColor: themeColors.accentStrong,
    backgroundColor: themeColors.accent,
  },
  stepDotText: {
    fontSize: 12,
    fontWeight: "700",
    color: themeColors.textMuted,
  },
  stepDotTextActive: {
    color: themeColors.white,
  },
  stepLabel: {
    fontSize: 11,
    color: themeColors.textSecondary,
    fontWeight: "600",
  },
  connectionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  connectionText: {
    fontSize: 12,
    color: themeColors.textMuted,
    flex: 1,
  },
  connectionError: {
    color: themeColors.error,
  },
  screenContent: {
    padding: 16,
    paddingBottom: 28,
    gap: 12,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: themeColors.textPrimary,
  },
  sectionDescription: {
    fontSize: 14,
    color: themeColors.textSecondary,
    marginBottom: 4,
  },
  sectionHint: {
    marginTop: 4,
    fontSize: 13,
    color: themeColors.textMuted,
  },
  sectionCard: {
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    borderRadius: 16,
    padding: 12,
    gap: 8,
  },
  sectionCardTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: themeColors.textPrimary,
  },
  sectionCardSubtitle: {
    fontSize: 13,
    color: themeColors.textSecondary,
  },
  actionStack: {
    gap: 8,
    marginTop: 2,
  },
  listBlock: {
    gap: 8,
  },
  patientRow: {
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    borderRadius: 16,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  patientRowMainAction: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  patientRowActive: {
    backgroundColor: themeColors.accentSoft,
    borderColor: themeColors.accentStrong,
  },
  patientName: {
    flex: 1,
    fontSize: 15,
    color: themeColors.textPrimary,
    fontWeight: "700",
  },
  patientSelect: {
    fontSize: 18,
  },
  patientDeleteButton: {
    width: 34,
    height: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surfaceElevated,
    alignItems: "center",
    justifyContent: "center",
  },
  patientDeleteButtonText: {
    fontSize: 16,
  },
  addPatientBox: {
    marginTop: 6,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    borderRadius: 16,
    padding: 12,
    gap: 10,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(94, 57, 113, 0.25)",
    justifyContent: "center",
    padding: 16,
  },
  modalOverlayTap: {
    ...StyleSheet.absoluteFillObject,
  },
  modalCard: {
    backgroundColor: themeColors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: themeColors.border,
    padding: 14,
    gap: 10,
    maxHeight: "86%",
  },
  newPatientForm: {
    gap: 8,
  },
  medicationCard: {
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surfaceElevated,
    borderRadius: 14,
    padding: 10,
    gap: 6,
    marginTop: 4,
  },
  exampleInfoCard: {
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    borderRadius: 16,
    padding: 12,
    gap: 4,
  },
  exampleInfoTitle: {
    fontSize: 14,
    color: themeColors.textPrimary,
    fontWeight: "800",
  },
  exampleInfoText: {
    fontSize: 13,
    color: themeColors.textSecondary,
    lineHeight: 18,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: themeColors.textPrimary,
  },
  input: {
    borderWidth: 1,
    borderColor: themeColors.border,
    borderRadius: 14,
    backgroundColor: themeColors.surfaceElevated,
    paddingHorizontal: 10,
    paddingVertical: 9,
    color: themeColors.textPrimary,
    fontSize: 15,
  },
  inputDisabled: {
    opacity: 0.6,
  },
  inputPressable: {
    justifyContent: "center",
  },
  birthInputText: {
    fontSize: 15,
    color: themeColors.textPrimary,
  },
  birthInputPlaceholder: {
    color: themeColors.textPlaceholder,
  },
  notesInput: {
    minHeight: 80,
    textAlignVertical: "top",
  },
  dateRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    width: "100%",
  },
  selectedDateBadge: {
    flex: 1,
    borderWidth: 1,
    borderColor: themeColors.border,
    borderRadius: 14,
    backgroundColor: themeColors.accentSoft,
    paddingHorizontal: 10,
    gap: 10,
    paddingVertical: 15,
  },
  selectedDateLabel: {
    color: themeColors.textPrimary,
    fontSize: 14,
    textAlign: "center",
    fontWeight: "700",
  },
  selectedDateIso: {
    color: themeColors.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  dateTodayButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  photoPreviewCard: {
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    borderRadius: 16,
    padding: 10,
    gap: 8,
  },
  photoPreviewCardEmpty: {
    borderStyle: "dashed",
    borderColor: themeColors.accentStrong,
    backgroundColor: themeColors.accentSoft,
  },
  photoPreviewTitle: {
    color: themeColors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  photoEmptyHint: {
    marginTop: 4,
    fontSize: 13,
    color: themeColors.textSecondary,
    fontWeight: "700",
  },
  photoPreviewImage: {
    width: "100%",
    height: 180,
    borderRadius: 14,
    backgroundColor: themeColors.surfaceElevated,
  },
  photoActionsRow: {
    flexDirection: "row",
    gap: 10,
  },
  photoHalfButton: {
    flex: 1,
  },
  calendarBox: {
    borderWidth: 1,
    borderColor: themeColors.border,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: themeColors.surface,
  },
  primaryButton: {
    marginTop: 6,
    backgroundColor: themeColors.accent,
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryButtonText: {
    color: themeColors.white,
    fontSize: 15,
    fontWeight: "800",
  },
  secondaryButton: {
    backgroundColor: themeColors.surfaceElevated,
    borderColor: themeColors.border,
    borderWidth: 1,
    borderRadius: 16,
    paddingVertical: 11,
    paddingHorizontal: 12,
    alignItems: "center",
  },
  secondaryButtonText: {
    color: themeColors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  horizontalActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  halfButton: {
    flex: 1,
    marginTop: 0,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    borderRadius: 16,
    padding: 12,
    gap: 10,
  },
  toggleRowActive: {
    backgroundColor: themeColors.accentSoft,
    borderColor: themeColors.accentStrong,
  },
  toggleEmoji: {
    fontSize: 20,
  },
  toggleLabel: {
    flex: 1,
    fontSize: 15,
    color: themeColors.textPrimary,
    fontWeight: "600",
  },
  toggleStatus: {
    fontSize: 20,
  },
  moodGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 6,
  },
  moodCard: {
    width: "47%",
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    borderRadius: 16,
    alignItems: "center",
    paddingVertical: 14,
  },
  moodCardSelected: {
    backgroundColor: themeColors.accentSoft,
    borderColor: themeColors.accentStrong,
  },
  moodEmoji: {
    fontSize: 28,
  },
  moodLabel: {
    marginTop: 5,
    fontSize: 13,
    color: themeColors.textPrimary,
    fontWeight: "700",
  },
  moodSubLabel: {
    marginTop: 4,
    fontSize: 12,
    color: themeColors.textSecondary,
    fontWeight: "600",
  },
  triggerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 2,
  },
  triggerChip: {
    backgroundColor: themeColors.surfaceElevated,
    borderColor: themeColors.border,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  triggerChipSelected: {
    backgroundColor: themeColors.accentSoft,
    borderColor: themeColors.accentStrong,
  },
  triggerChipText: {
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  odontogramNumberRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  odontogramNumberInput: {
    flex: 1,
  },
  odontogramNumberButton: {
    marginTop: 0,
    paddingHorizontal: 12,
  },
  toothGrid: {
    flexDirection: "column",
    gap: 8,
  },
  toothRowTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: themeColors.textSecondary,
    marginTop: 2,
  },
  toothRowScroll: {
    flexDirection: "row",
    gap: 8,
    paddingVertical: 2,
    paddingRight: 4,
    alignItems: "center",
  },
  toothMidSeparator: {
    width: 2,
    height: 52,
    borderRadius: 99,
    backgroundColor: themeColors.borderStrong,
    marginHorizontal: 2,
  },
  toothCard: {
    width: 54,
    position: "relative",
    borderWidth: 1,
    borderColor: themeColors.border,
    borderRadius: 12,
    backgroundColor: themeColors.surfaceElevated,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    gap: 2,
  },
  toothCardFilled: {
    borderColor: themeColors.accentStrong,
    backgroundColor: themeColors.accentSoft,
  },
  toothCardEmoji: {
    fontSize: 16,
  },
  toothCardLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: themeColors.textPrimary,
  },
  toothCardMissingX: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -8 }, { translateY: -12 }],
    color: themeColors.error,
    fontSize: 24,
    fontWeight: "900",
    lineHeight: 24,
  },
  progressRow: {
    gap: 7,
    backgroundColor: themeColors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: themeColors.border,
    padding: 11,
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  progressLabel: {
    fontSize: 14,
    color: themeColors.textPrimary,
    fontWeight: "600",
    flex: 1,
    paddingRight: 10,
  },
  progressValue: {
    fontSize: 14,
    color: themeColors.textSecondary,
    fontWeight: "700",
  },
  progressTrack: {
    height: 10,
    backgroundColor: themeColors.surfaceElevated,
    borderRadius: 999,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: themeColors.accentStrong,
    borderRadius: 999,
  },
  historyPhotoCard: {
    backgroundColor: themeColors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: themeColors.border,
    padding: 10,
    gap: 8,
  },
  historyPhotoTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: themeColors.textPrimary,
  },
  historyPhotoImage: {
    width: "100%",
    height: 220,
    borderRadius: 14,
    backgroundColor: themeColors.surfaceElevated,
  },
  galleryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  galleryImage: {
    width: "48%",
    height: "100%",
    aspectRatio: 1,
    borderRadius: 14,
    backgroundColor: themeColors.surfaceElevated,
    borderWidth: 1,
    borderColor: themeColors.border,
  },
  fullscreenBackdrop: {
    flex: 1,
    backgroundColor: "rgba(94, 57, 113, 0.7)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  fullscreenContent: {
    width: "100%",
    gap: 10,
    alignItems: "center",
  },
  fullscreenImage: {
    width: "100%",
    height: "80%",
    borderRadius: 18,
    backgroundColor: themeColors.surface,
  },
  fullscreenCaption: {
    color: themeColors.textPrimary,
    fontSize: 15,
    fontWeight: "700",
  },
});
